# Generated by Django 3.2.7 on 2021-09-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnabledDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Fecha habilitada',
                'verbose_name_plural': 'Fechas habilitadas',
            },
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='menu',
            name='enabled_dates',
            field=models.ManyToManyField(related_name='menus', to='api.EnabledDate', verbose_name='Fechas habilitadas'),
        ),
    ]
