# Generated by Django 3.2.7 on 2021-09-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='campus',
            field=models.ManyToManyField(related_name='campus_menus', to='api.Campus', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='enabled_dates',
            field=models.ManyToManyField(related_name='dates_menus', to='api.EnabledDate', verbose_name='Fechas habilitadas'),
        ),
    ]
