# Generated by Django 3.2.7 on 2021-10-06 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='enabled_dates',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='servings',
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.IntegerField(choices=[(0, 'OTRO'), (1, 'ENTRADA'), (2, 'PRINCIPAL'), (3, 'BEBIDA'), (4, 'POSTRE')], default=0),
        ),
        migrations.AlterField(
            model_name='ingredientswithmeasure',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_component', to='api.component'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='MenuWithDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.IntegerField(blank=True, null=True, verbose_name='Porciones')),
                ('campus', models.ManyToManyField(blank=True, related_name='campus_menus_dates', to='api.Campus', verbose_name='Sede')),
                ('date', models.ManyToManyField(blank=True, related_name='date_menu_campus', to='api.EnabledDate')),
                ('menu', models.ManyToManyField(related_name='menu_date_campus', to='api.Menu')),
            ],
            options={
                'verbose_name': 'Menu con fecha habilitada',
                'verbose_name_plural': 'Menus con fechas habilitadas',
            },
        ),
    ]
