# Generated by Django 3.2.7 on 2021-10-07 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211006_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuwithdate',
            name='campus',
        ),
        migrations.AddField(
            model_name='menuwithdate',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_date_menus', to='api.campus'),
        ),
        migrations.RemoveField(
            model_name='menuwithdate',
            name='date',
        ),
        migrations.AddField(
            model_name='menuwithdate',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.RemoveField(
            model_name='menuwithdate',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuwithdate',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_date_campus', to='api.menu'),
        ),
    ]
