# Generated by Django 3.2.7 on 2021-09-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210928_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='ingredients',
            field=models.ManyToManyField(through='api.IngredientsWithMeasure', to='api.Ingredient', verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='ingredientswithmeasure',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_component', to='api.component'),
        ),
    ]
