# Generated by Django 3.2.7 on 2021-11-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticket_canjeado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='canjeado',
            field=models.BooleanField(default=False, verbose_name='Canjeado'),
        ),
    ]
